version: '3'
services:
  nosql-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - nosql-db